export const searchIndex = [
  {
    title: "Introduction & Overview",
    category: "Getting Started",
    description: "What is Subatom Infer, core mental model, and dual sync/async validation.",
    keywords: ["intro", "overview", "subatom", "infer", "validation", "runtime", "types"],
    href: "/docs",
  },
  {
    title: "Why Runtime Validation?",
    category: "Getting Started",
    description: "TypeScript compile-time erasure vs real runtime data boundaries.",
    keywords: ["why", "boundary", "typescript", "runtime", "security", "pollution"],
    href: "/docs/why-subatom-infer",
  },
  {
    title: "Installation & Setup",
    category: "Getting Started",
    description: "Install subatom-infer with npm, pnpm, yarn, or bun.",
    keywords: ["install", "npm", "pnpm", "yarn", "bun", "node", "setup"],
    href: "/docs/installation",
  },
  {
    title: "Quick Start Guide",
    category: "Getting Started",
    description: "First schema, validation, safeParse, and Infer types in 3 minutes.",
    keywords: ["quickstart", "first", "start", "tutorial", "guide"],
    href: "/docs/quick-start",
  },
  {
    title: "Primitives & Literals",
    category: "Schema Types",
    description: "Strings, numbers, bigints, booleans, dates, literals, and unit types.",
    keywords: [
      "string",
      "number",
      "bigint",
      "boolean",
      "date",
      "literal",
      "null",
      "undefined",
      "uuid",
      "email",
    ],
    href: "/docs/primitives",
  },
  {
    title: "Type Coercion Suite",
    category: "Schema Types",
    description: "Coerce strings from forms and queries into typed numbers, booleans, and dates.",
    keywords: ["coerce", "form", "query", "boolean", "number", "date", "params"],
    href: "/docs/coercion",
  },
  {
    title: "Objects & Shapes",
    category: "Schema Types",
    description: "Object strictness policies, extend, merge, pick, omit, and deepPartial.",
    keywords: [
      "object",
      "strict",
      "passthrough",
      "strip",
      "catchall",
      "extend",
      "merge",
      "pick",
      "omit",
      "partial",
    ],
    href: "/docs/objects",
  },
  {
    title: "Arrays & Collections",
    category: "Schema Types",
    description: "Arrays, tuples, ES6 Sets, ES6 Maps, and dynamic records.",
    keywords: ["array", "tuple", "set", "map", "record", "nonempty", "collections"],
    href: "/docs/collections",
  },
  {
    title: "Enums & Unions",
    category: "Schema Types",
    description: "Enums, native TypeScript enums, O(1) discriminated unions, and lazy schemas.",
    keywords: ["enum", "nativeEnum", "union", "discriminatedUnion", "lazy", "recursive"],
    href: "/docs/enums-and-unions",
  },
  {
    title: "Modifiers & Pipelines",
    category: "Modifiers & Pipelines",
    description: "optional, nullable, defaults, prefaults, transforms, pipes, and branding.",
    keywords: [
      "optional",
      "nullable",
      "default",
      "prefault",
      "transform",
      "pipe",
      "catch",
      "brand",
      "codec",
    ],
    href: "/docs/modifiers",
  },
  {
    title: "Refinements & Custom Checks",
    category: "Modifiers & Pipelines",
    description: "Single-predicate refine and multi-issue superRefine with path tracking.",
    keywords: ["refine", "superRefine", "custom", "async", "password", "cross-field"],
    href: "/docs/refinements",
  },
  {
    title: "Files & Upload Validation",
    category: "Modifiers & Pipelines",
    description: "Single and multi-part upload validation, MIME constraints, and storage types.",
    keywords: ["file", "files", "upload", "mime", "multipart", "storage"],
    href: "/docs/file-uploads",
  },
  {
    title: "Functions & Promises",
    category: "Modifiers & Pipelines",
    description: "Validate function arguments and returns, or unpack Promise resolutions.",
    keywords: ["function", "promise", "async", "wrapper", "unwrap"],
    href: "/docs/functions-and-promises",
  },
  {
    title: "Execution & Safe Parsing",
    category: "Engine & Diagnostics",
    description: "Compare parse, safeParse, parseAsync, and safeParseAsync.",
    keywords: ["parse", "safeParse", "parseAsync", "safeParseAsync", "spa", "execute"],
    href: "/docs/execution-and-parsing",
  },
  {
    title: "Errors & Diagnostic Tree",
    category: "Engine & Diagnostics",
    description: "ValidationError, format(), flatten(), and prettifyError() output.",
    keywords: ["error", "validationerror", "format", "flatten", "prettify", "issues"],
    href: "/docs/errors-and-diagnostics",
  },
  {
    title: "TypeScript Type Inference",
    category: "Engine & Diagnostics",
    description: "Infer, Output, Input, and DeepReadonly type utilities.",
    keywords: ["infer", "output", "input", "type", "typescript", "types", "deepreadonly"],
    href: "/docs/typescript-inference",
  },
  {
    title: "HTTP & API Validation",
    category: "Production Guides",
    description: "Next.js Route Handlers and Node.js REST API validation patterns.",
    keywords: ["api", "nextjs", "http", "route", "handler", "request", "body"],
    href: "/docs/guides-api-validation",
  },
  {
    title: "Environment Variables Validation",
    category: "Production Guides",
    description: "Validate process.env on boot with fail-fast guarantees.",
    keywords: ["env", "process.env", "config", "port", "boot"],
    href: "/docs/guides-env-validation",
  },
  {
    title: "Full API Reference",
    category: "Production Guides",
    description: "Complete cheat-sheet of every factory, modifier, and method in Subatom Infer.",
    keywords: ["api", "reference", "methods", "cheatsheet", "catalog"],
    href: "/docs/api-reference",
  },
];
